#!/usr/bin/env python
"""Build the reproducible synthetic dataset, then evaluate + train the models.

One deterministic command stands the whole modeling story up from nothing:

  uv run python -m scripts.seed_and_train

It (1) synthesizes a 45-day, 5-station hourly history, (2) runs it through the **real**
validation → quarantine → interpolation → store pipeline (proving gate G1 end to end,
including the injected bad batch and interpolation flags), (3) builds features, (4) scores
the model against the persistence and seasonal baselines with walk-forward CV, (5) fits the
final per-pollutant models, and (6) writes the committed evidence: ``models/registry.json``,
``data/features/baseline_metrics.json``, and ``models/MODEL_CARD.md``.

Because every step is seeded, the numbers are identical on every machine and every run.
"""

import os

# Pin BLAS/OpenMP to a single thread *before* importing numpy/sklearn so the
# gradient-boosted histograms reduce in a fixed order — without this, multi-threaded
# floating-point non-determinism flips borderline (pollutant x horizon) verdicts between
# runs, which would make the committed metrics irreproducible.
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")

import json
import logging
from pathlib import Path
from typing import Any

import joblib
import pandas as pd
from app.config import get_settings
from app.ingestion.interpolation import interpolate_series
from app.ingestion.storage import (
    ProcessedStore,
    QuarantineStore,
    default_data_dir,
)
from app.ingestion.validation import validate_batch
from app.ingestion.weather_store import WeatherStore
from app.logging_config import configure_logging
from app.modeling import synthetic
from app.modeling.features import build_features
from app.modeling.train import HORIZONS, MODEL_VERSION, build_registry, generated_at

logger = logging.getLogger("uaqf.scripts.seed_and_train")


def _ingest_synthetic(data_dir: Path) -> dict[str, int]:
    """Run synthetic raw data through the production validate → interpolate → store path."""
    processed = ProcessedStore(data_dir / "processed" / "measurements.parquet")
    quarantine = QuarantineStore(data_dir / "processed" / "quarantine.parquet")
    weather = WeatherStore(data_dir / "processed" / "weather.parquet")

    # Rebuild from scratch so the dataset is deterministic (no stale rows from a prior run).
    for p in (
        data_dir / "processed" / "measurements.parquet",
        data_dir / "processed" / "quarantine.parquet",
        data_dir / "processed" / "weather.parquet",
    ):
        p.unlink(missing_ok=True)

    syn = synthetic.generate()

    report = validate_batch(syn.measurements)
    if report.quarantined:
        quarantine.append(report.quarantined)
    interpolated = interpolate_series(report.accepted)
    processed.upsert(interpolated)
    weather.upsert(syn.weather)

    n_interp = sum(1 for m in interpolated if m.interpolated)
    stats = {
        "raw": len(syn.measurements),
        "injected_bad": syn.injected_bad,
        "quarantined": report.quarantined_count,
        "gaps_detected": len(report.gaps),
        "interpolated_points": n_interp,
        "accepted": len(interpolated),
        "weather": len(syn.weather),
    }
    logger.info("synthetic_ingested", extra=stats)
    return stats


def _write_baseline_metrics(registry: dict[str, Any], data_dir: Path) -> None:
    """Emit baseline_metrics.json in the shape evaluate_baselines already produced."""
    out = {
        pol: {
            "persistence": entry["baselines"]["persistence"],
            "seasonal": entry["baselines"]["seasonal"],
        }
        for pol, entry in registry.items()
    }
    path = data_dir / "features" / "baseline_metrics.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=2), encoding="utf-8")


def _write_model_card(registry: dict[str, Any], ingest: dict[str, Any], models_dir: Path) -> None:
    lines: list[str] = []
    a = lines.append
    a("# Model Card — Atmosphere Air-Quality Forecaster")
    a("")
    a(f"*Generated by `scripts/seed_and_train.py` on {generated_at()}. Do not edit by hand.*")
    a("")
    a("## Model")
    a("")
    a("- **Architecture:** `HistGradientBoostingRegressor` (scikit-learn), one model per "
      "pollutant.")
    a(f"- **Version:** `{MODEL_VERSION}`")
    a("- **Framing:** direct multi-step — `horizon` (1-24h) is an explicit input feature.")
    a("- **Features:** cyclical hour/day-of-week, 1h & 24h lags, 24h rolling mean, and "
      "weather (temperature, humidity, wind speed, pressure).")
    a("")
    a("## Training data (reproducible synthetic backfill)")
    a("")
    a("To keep the repo runnable without paid API keys, models are trained on a "
      "**deterministic synthetic** hourly history generated by `app/modeling/synthetic.py` "
      "and pushed through the *same* validation/interpolation pipeline as live data. Swap in "
      "a real point-in-time pull and re-run — features, evaluation, and contract are unchanged.")
    a("")
    a(f"- Raw readings: **{ingest['raw']:,}** across {ingest['weather']:,} weather rows")
    a(f"- Quarantined (out-of-range, injected): **{ingest['quarantined']}** — proves the G1 "
      "bad-batch path")
    a(f"- Gaps detected: **{ingest['gaps_detected']}**, interpolated & flagged points: "
      f"**{ingest['interpolated_points']}** (HL3)")
    a("")
    a("## Performance vs baselines (gate G2, walk-forward CV)")
    a("")
    a("Rolling-origin cross-validation; to certify, the model must beat **both** persistence "
      "and the seasonal average on **both** MAE and RMSE by a meaningful (>=1%) margin at "
      "**every** horizon. Values below are averaged across horizons 1-24h; per-horizon detail "
      "lives in `registry.json`.")
    a("")
    a("| Pollutant | Model MAE | Persistence MAE | Seasonal MAE | Model RMSE | Beats both? | "
      "Horizons |")
    a("|-----------|-----------|-----------------|--------------|------------|-------------|"
      "----------|")
    for pol, entry in registry.items():
        s = entry["summary"]
        beat = "yes" if entry["beats_baseline"] else "no"
        a(
            f"| {pol.upper()} | {s['model']['mae']:.2f} | {s['persistence']['mae']:.2f} | "
            f"{s['seasonal']['mae']:.2f} | {s['model']['rmse']:.2f} | {beat} | "
            f"{entry['horizons_beaten']}/{entry['horizons_scored']} |"
        )
    a("")
    a("The gate is enforced **per pollutant** (HL2): a pollutant that does not clear it at "
      "every horizon is *not* served by the model — the API degrades to the persistence "
      "forecast with `beats_baseline=false`. A pollutant typically misses on the 24h horizon "
      "alone, where 'same hour yesterday' persistence is naturally near-optimal and the model "
      "is only at parity; it still wins comfortably on the horizon-averaged aggregate.")
    a("")
    a("Exceedance thresholds (Unhealthy-for-Sensitive-Groups) used for event recall: "
      "PM2.5 35.4 ug/m3, O3 70 ppb, NO2 100 ppb.")
    a("")
    a("## Known failure modes")
    a("")
    a("- **Sudden fronts / events:** lag-driven; an unprecedented spike (wildfire smoke, "
      "fireworks) is under-predicted on its first hours.")
    a("- **Sensor outage:** gaps beyond the interpolation limit are shown as gaps, never "
      "invented; stale inputs are flagged (HL1/HL3).")
    a("- **Synthetic ceiling:** real sensors are noisier; expect baseline margins to compress "
      "on live data — re-run this script on a real pull to re-certify G2.")
    a("")
    a("## Refresh cadence")
    a("")
    a("Retrain weekly (or on a fresh ingest window) via `scripts/train_model.py` for live "
      "data, or `scripts/seed_and_train.py` for the reproducible demo.")
    a("")
    (models_dir / "MODEL_CARD.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    settings = get_settings()
    configure_logging(settings.log_level)

    data_dir = default_data_dir()
    models_dir = data_dir.parent / "models"
    models_dir.mkdir(parents=True, exist_ok=True)

    logger.info("seed_and_train_started")
    ingest = _ingest_synthetic(data_dir)

    build_features(data_dir)
    features_path = data_dir / "features" / "features.parquet"
    df = pd.read_parquet(features_path)
    logger.info("features_loaded", extra={"rows": len(df)})

    registry, models = build_registry(df, HORIZONS)
    if not registry:
        raise SystemExit("No pollutant accumulated enough data to evaluate — aborting.")

    for pol, model in models.items():
        joblib.dump(model, models_dir / f"{pol}_model.joblib")

    (models_dir / "registry.json").write_text(json.dumps(registry, indent=2), encoding="utf-8")
    _write_baseline_metrics(registry, data_dir)
    _write_model_card(registry, ingest, models_dir)

    for pol, entry in registry.items():
        logger.info(
            "model_certified",
            extra={
                "pollutant": pol,
                "beats_baseline": entry["beats_baseline"],
                "model_mae": round(entry["summary"]["model"]["mae"], 3),
                "persistence_mae": round(entry["summary"]["persistence"]["mae"], 3),
            },
        )
    logger.info("seed_and_train_completed")


if __name__ == "__main__":
    main()
