/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and data freshness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitoring stations */
        get: operations["list_stations_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast for a station */
        get: operations["get_forecast_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AQICategory
         * @description US EPA AQI categories (display + color encoding only — see HL4).
         * @enum {string}
         */
        AQICategory: "good" | "moderate" | "unhealthy_sensitive" | "unhealthy" | "very_unhealthy" | "hazardous";
        /** Coordinates */
        Coordinates: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * DataSource
         * @description Provenance of a payload so the UI can be honest about what it shows.
         * @enum {string}
         */
        DataSource: "live" | "seed" | "cache";
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Value
             * @description Predicted concentration; never negative.
             */
            value: number;
            /**
             * Lower
             * @description Confidence-interval lower bound.
             */
            lower: number;
            /**
             * Upper
             * @description Confidence-interval upper bound.
             */
            upper: number;
            /**
             * Baseline
             * @description HL2 — persistence-baseline value at this ts.
             */
            baseline: number;
            /** Aqi */
            aqi: number;
            category: components["schemas"]["AQICategory"];
            /**
             * Interpolated
             * @description HL3 — true if derived from imputed inputs.
             */
            interpolated: boolean;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Station Id */
            station_id: string;
            /** Station Name */
            station_name: string;
            pollutant: components["schemas"]["Pollutant"];
            /** Unit */
            unit: string;
            /** Horizon Hours */
            horizon_hours: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Data As Of
             * Format: date-time
             * @description HL1 — freshness of the inputs.
             */
            data_as_of: string;
            /**
             * Stale
             * @description HL1.
             */
            stale: boolean;
            data_source: components["schemas"]["DataSource"];
            /**
             * Model Version
             * @description HL2 — identifies the serving model.
             */
            model_version: string;
            /**
             * Baseline Label
             * @description HL2 — name of the baseline (e.g. 'persistence').
             */
            baseline_label: string;
            /**
             * Beats Baseline
             * @description HL2 — whether the model beats the baseline on the validation window.
             */
            beats_baseline: boolean;
            /**
             * Disclaimer
             * @description HL4 — not-medical-guidance notice.
             */
            disclaimer: string;
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /**
             * Last Refresh
             * @description When forecasts were last refreshed; null before Phase 1.
             */
            last_refresh?: string | null;
            /** Data As Of */
            data_as_of?: string | null;
            /** Upstreams */
            upstreams: components["schemas"]["ProviderHealth"][];
            /** Cache Hit Rate */
            cache_hit_rate?: number | null;
        };
        /**
         * LatestReading
         * @description Most recent observed value for one pollutant at a station.
         */
        LatestReading: {
            pollutant: components["schemas"]["Pollutant"];
            /**
             * Value
             * @description Concentration; never negative.
             */
            value: number;
            /** Unit */
            unit: string;
            /** Aqi */
            aqi: number;
            category: components["schemas"]["AQICategory"];
            /**
             * Interpolated
             * @description HL3 — true if imputed, not measured.
             */
            interpolated: boolean;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /**
         * Pollutant
         * @description Pollutants this app forecasts.
         * @enum {string}
         */
        Pollutant: "pm25" | "o3" | "no2";
        /** ProviderHealth */
        ProviderHealth: {
            /** Name */
            name: string;
            status: components["schemas"]["UpstreamStatus"];
            /** Last Success */
            last_success?: string | null;
        };
        /** Station */
        Station: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Country */
            country: string;
            coordinates: components["schemas"]["Coordinates"];
            /** Pollutants */
            pollutants: components["schemas"]["Pollutant"][];
            /** Latest */
            latest: components["schemas"]["LatestReading"][];
            /**
             * Data As Of
             * Format: date-time
             * @description HL1 — freshness of this station's data.
             */
            data_as_of: string;
            /**
             * Stale
             * @description HL1 — true when data_as_of is older than the threshold.
             */
            stale: boolean;
            data_source: components["schemas"]["DataSource"];
        };
        /**
         * UpstreamStatus
         * @enum {string}
         */
        UpstreamStatus: "ok" | "degraded" | "down" | "unknown";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_stations_stations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Station"][];
                };
            };
        };
    };
    get_forecast_forecast_get: {
        parameters: {
            query: {
                /** @description Station id from /stations. */
                station_id: string;
                /** @description Pollutant to forecast. */
                pollutant?: components["schemas"]["Pollutant"];
                /** @description Hours ahead (1..max_horizon). */
                horizon?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
